name: Run Tests

on:
  push:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Start CouchDB container
        run: |
          docker run -d --name couchdb-test \
            -p 5984:5984 \
            -e COUCHDB_USER=admin \
            -e COUCHDB_PASSWORD=admin \
            couchdb:latest

      - name: Initialize CouchDB
        run: |
          until curl -X GET http://admin:admin@localhost:5984/_all_dbs; do
            echo "Waiting for CouchDB to be ready..."
            sleep 5
          done
          curl -X PUT http://admin:admin@localhost:5984/_users

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r fast-point-api/requirements.txt

      - name: Install pytest
        run: pip install pytest

      - name: Run specific pytest file
        working-directory: fast-point-api
        run: pytest -v ./tests/test_couchdb_api.py
