name: Run Tests

on:
  push:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      couchdb:
        image: couchdb:latest
        ports:
          - 5984:5984
        options: >-
          --env COUCHDB_USER=admin
          --env COUCHDB_PASSWORD=admin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r fast-point-api/requirements.txt

      - name: Run specific pytest file
        working-directory: fast-point-api
        run: pytest -v ./tests/test_couchdb_api.py
